import { Text, VStack } from "@yamada-ui/react";

export const HomeLayout = () => (
  <VStack gap={1}>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
    <Text>aaaa</Text>
  </VStack>
);
